FROM python:3.9

COPY ./requirements_app.txt /requirements_app.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /requirements_app.txt
RUN pip install --no-cache-dir fastapi uvicorn mlflow 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]